token:
  expiration_time: 864000000
  secret: "{cipher}AQCc634KjStzORdDet3yIxQDj8CApnRcckYLGcp5VGPE3y92Glh5IqAoPJRoLAPouE5u55kAz+/0r4DRikOJAhdr7Iyx0wcmjeEqA+0E8r6SXQtgZa6EJ1OyI4Ka5m2v4dUcedyiZyQvrgibuHjQUcOHinqiguEGqscJXAal3ptQda9S6w1DbgNkspaPTy0jTWweDQj0dNJRiNP/nkhqQu50O4RvIFytotr4m1g4ELzFOoMRHDY0yUt0pm0K5581K5mN8hWEcsB8oqSsn86PPH7LtyZkx2ZS5/jRK0lLjwW1zbV2hz0ZH6qaOnfO1gtnRPT8CoOnL14WMoAIsUVRqvLysH3oAst18AbMJpm1PBBPD0kwnp9VlUKtuiBXOVQbu6TGBcumz1uUMay16H0hZIUb"

gateway:
  ip: 192.168.1.4
